# Air configuration

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server.exe server.go"
  bin = "tmp/server.exe"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  delay = 1000
  log = "build-errors.log"
  send_interrupt = true
  kill_delay = 500

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
  error = "red"

[misc]
  clean_on_exit = true
