// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Chat struct {
	Query     string `json:"query"`
	Answer    string `json:"answer"`
	UserID    string `json:"userID"`
	Timestamp string `json:"timestamp"`
}

type ContentInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	URL         string `json:"url"`
	Image       string `json:"image"`
	Type        string `json:"type"`
}

type DeleteAllChatResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type InitialMessageInput struct {
	UserID string `json:"userID"`
}

type Mutation struct {
}

type Query struct {
}

type QueryInput struct {
	Query  string `json:"query"`
	UserID string `json:"userId"`
}

type QueryResponse struct {
	Response string `json:"response"`
}

type SuccessEvent struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}
